### ISSUE TITLE
Storing values containing a $ character in them results in truncation of value when retrieved

### ISSUE THREAD

**Issue by jarrodmirabito** [fugue/credstash#155]
Store a value by executing something like: 

credstash -t TABLE_NAME put keyname "Test$Test"

When retrieving the value, only "Test" is returned.  Anything from the $ onwards (including the $ char) is dropped.

credstash: v1.13.2
python --version: Python 2.7.10
(Darwin Kernel Version 16.6.0)

**Comment by nathan-muir** [comment]
The issue is caused by your PUT command, and running it in bash / most terminals.

`"Test$Test"` converts to `"Test${Test}"`, so it looks up the value of `Test` which is probably nothing, thus it stores only `"Test"`

In terminals like Bash, you can disable variable interpolation in strings by using `'`  instead of `"`.

eg,

```sh
credstash -t TABLE_NAME put keyname 'Test$Test'
```

**Comment by jarrodmirabito** [comment]
Thanks, that worked.
