### ISSUE TITLE
Question: can i also insert certificates content?

### ISSUE THREAD

**Issue by DanyC97** [fugue/credstash#68]
In addition to store passwords i'd also like to store certificates (the content of it), will that be possible? Asking as i believe there is a limitation in input size?

**Comment by deyvsh** [comment]
I've managed to store an encrypted 4096-bit private RSA key in credstash with no problems at all.

**Comment by alex-luminal** [comment]
The max DDB record size is 400 KB. Credstash uses a couple KB for the version, key, hmac key, etc, but it's very little overhead. 

We put 4k certs in credstash no problem.

**Comment by DanyC97** [comment]
Superb, much thanks @alex-luminal  @deyvsh  :+1:

**Comment by babineaum** [comment]
I know this is closed but could someone help me figure out how to format the key, i seem to get 
`----- START KEY--------- sadfkasjdfkljasdfkjasdlkjfaslkjdfkl skljdflkasjdflksadjflkasdjflkajs kaljdsfklasdjfklasjdfklsaj  dklasfjdsalkjfasdlkjfklsja`
instead of
`-------START KEY -------`
`sakfdlkajsdflkjaslkdfjaslkdfjasldkjflkasj`
`sljfakldasjfklsadjflkasdjfklasdjflkasdjflk`
