### ISSUE TITLE
Use of Key Grants

### ISSUE THREAD

**Issue by ayavorsk2000-gmail** [fugue/credstash#83]
Great little utility! We are looking to utilize it but we need to constrain each service to specific encryption context. In your documentation you state the following:

"They are also useful for constraining access to a given credstash stored credential by using KMS Key Policy conditions and KMS Grant conditions. Doing so allows you to, for example, make sure that your database servers and web-servers can read the web-server DB user password but your database servers can not read your web-servers TLS/SSL certificate's private key."

Could you please elaborate or perhaps include an example of how one can use Key Grants to accomplish above? 

Thanks,
Alex

**Comment by alsmola** [comment]
Here's a short blurb I wrote up that may be helpful:

KMS encryption and decryption operations allow you to pass an “encryption context”. This is additional data (represented as key-value pairs) that, if supplied during encryption, must also be supplied during decryption.

KMS key grants permit access to KMS keys by AWS IAM users or roles. You can specify operations (e.g. `Decrypt`) and *mandate an encryption context*.

These two features combined let us restrict access to secrets by services.

When you write a secret, you could supply an environment string (e.g. `production` or `development`) and a service name. Then, you could use these values to create the following encryption context and include it in the encryption operation:

`“environment:production,service:service-name”`

These are included in the encryption context for the secret, and are thus tied to the secret.You must provide these exact same context variables (environment and service) when decrypting the secret.

You would then create a key grant for the production service user could specify that they can only use the KMS credstash key for decryption if they send the `“environment:production,service:service-name”` encryption context:

`aws kms create-grant --key-id $STEALTH_KEY --grantee-principal "arn:aws:iam::0000000000:role/service-name" --constraints "EncryptionContextEquals={environment=production,service=service-name}" --operations Decrypt`

This way, the service user/role could only get access to the secrets they are intended to get access to. They couldn’t decrypt the secrets for a different service, or a different environment, because they wouldn’t have access to decrypting with that encryption context.

**Comment by alex-luminal** [comment]
Thanks for writing this up. I copied it to the credstash wiki (https://github.com/fugue/credstash/wiki/Using-Key-Grants-and-Encryption-Contexts-to-restrict-access) for future reference.

I'm going to close this issue for now, but feel free to reopen if ^ didnt answer your issue.
