### ISSUE TITLE
Reliance on pycrypto problematic?

### ISSUE THREAD

**Issue by endofcake** [fugue/credstash#96]
It looks like `pycrypto` project [is dead](https://github.com/dlitz/pycrypto/issues/173) and also has a [security vulnerability](https://pony7.fr/ctf:public:32c3:cryptmsg). Is this a problem for `credstash`?

`pycrypto` also makes it quite tricky to install `credstash` on Windows, it looks like there are alternatives which [make installation simpler](https://github.com/paramiko/paramiko/pull/394).

**Comment by alex-luminal** [comment]
That vulnerability probably isnt a big deal for credstash since without IAM
access to the material in DDB and the KMS key, you cant really do anything.
And if you have access to KMS and DDB, then you dont really need to be
exploiting credstash, you can just decrypt the item.

WRT pycryto being dead, we should probably start looking into porting to
something like pycryptodome.

On Thu, Sep 8, 2016 at 12:35 AM, Alexander Savchuk <notifications@github.com

**Comment by edyesed** [comment]
What's the purpose behind leveraging an additional crypto library outside of KMS?
